### ISSUE TITLE
Fix "DescribeIdentityException: Error on describing cognito identity" error

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#169]
```javascript
DescribeIdentityException: Error on describing cognito identity us-east-1:d24896da-1658-479c-8623-69ace60acef0. AccessDeniedExc…
  at Request.<anonymous>(/js/lib/deep-framework.js:33:196)
  at Request.<anonymous>(/js/lib/deep-framework.js:32:27554)
  at ? (/js/lib/deep-framework.js:34:3149)
  at AcceptorStateMachine.runTo(/js/lib/deep-framework.js:34:2824)
  at Request.transition(/js/lib/deep-framework.js:32:27269)
  at Request.emit(/js/lib/deep-framework.js:33:121)
  at Request.emit(/js/lib/deep-framework.js:33:8100)
  at Request.callListeners(/js/lib/deep-framework.js:33:8641)
  at Request.<anonymous>(/js/lib/deep-framework.js:32:29120)
  at Response.<anonymous>(/js/lib/deep-framework.js:30:23653)
```

**Comment by mgoria** [comment]
This issue is fixed in `deep-framework@1.5.13`
