### ISSUE TITLE
Fix "TypeError: Cannot read property 'hasOwnProperty' of null"

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#170]
- Login to DEEP Marketplace 
- Add 'ToDo application' to Cart 
- Input valid data into 'Billing Management and AWS Credentials fields' 
- Click on 'Checkout' button and deploy the application 
- Go to 'Account' page after finishing the deploy 
- Click on 'Account' 
- Click on 'Billing Management' 
- Click in 'Payment Receipts'

BUG :

Cannot read property 'hasOwnProperty' of null error while clicking on Payment Receipts

```javascript
TypeError: Cannot read property 'hasOwnProperty' of null
  at ? (/js/lib/deep-framework.js:34:3149)
  at AcceptorStateMachine.runTo(/js/lib/deep-framework.js:34:2824)
  at Request.transition(/js/lib/deep-framework.js:32:27269)
  at Request.emit(/js/lib/deep-framework.js:33:121)
  at Request.emit(/js/lib/deep-framework.js:33:8100)
  at Request.callListeners(/js/lib/deep-framework.js:33:8641)
  at Request.<anonymous>(/js/lib/deep-framework.js:32:29120)
  at Response.<anonymous>(/js/lib/deep-framework.js:23:31572)
  at new LambdaResponse(/js/lib/deep-framework.js:23:17543)
  at LambdaResponse._decodePayload(/js/lib/deep-framework.js:23:18554)
```

**Comment by mgoria** [comment]
This issue is fixed in `deep-framework@1.5.13`
