### ISSUE TITLE
Fix "QuotaExceededError: Failed to execute 'setItem' on 'Storage'" error

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#178]
```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'us-east-1:e4199d66-de84-4961-83f2-e7…
  at ? (/js/lib/deep-framework.js:29:28596)
  at ? (/js/lib/deep-framework.js:29:27250)
  at AWS.CognitoSyncManager.Dataset.CognitoSyncDataset.put(/js/lib/deep-framework.js:35:7294)
  at AWS.CognitoSyncManager.LocalStorage.CognitoSyncLocalStorage.putValue(/js/lib/deep-framework.js:35:23567)
  at AWS.CognitoSyncManager.LocalStorage.CognitoSyncLocalStorage.getRecord(/js/lib/deep-framework.js:35:26221)
  at AWS.CognitoSyncManager.StoreLocalStorage.CognitoSyncStoreLocalStorage.get(/js/lib/deep-framework.js:36:8654)
  at ? (/js/lib/deep-framework.js:35:26355)
  at ? (/js/lib/deep-framework.js:35:23889)
  at AWS.CognitoSyncManager.StoreLocalStorage.CognitoSyncStoreLocalStorage.set(/js/lib/deep-framework.js:36:9221)
```

**Comment by mgoria** [comment]
This issue is fixed in `deep-framework@1.5.15`
