### ISSUE TITLE
Logged user cannot be loaded inside lambda function

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#321]
When trying to load logged user into lambda runtime it throws an error:

```
{
    "errorMessage": "{\"errorType\":\"SyntaxError\",\"errorMessage\":\"Unexpected token u\",\"errorStack\":\"SyntaxError: Unexpected token u\\n    at Object.parse (native)\\n    at /var/task/deep_modules/deep-security@1.8.5/lib.compiled/UserProvider.js:46:30\\n    at decoratedCallback (/var/task/deep_modules/deep-resource@1.8.3/lib.compiled/Resource/Request.js:412:9)\\n    at /var/task/deep_modules/deep-resource@1.8.3/lib.compiled/Resource/Request.js:596:11\\n    at Request.callback (/var/task/deep_modules/superagent@1.8.3/lib/node/index.js:1:6866)\\n    at IncomingMessage.<anonymous> (/var/task/deep_modules/superagent@1.8.3/lib/node/index.js:1:10680)\\n    at IncomingMessage.emit (events.js:117:20)\\n    at _stream_readable.js:944:16\\n    at process._tickDomainCallback (node.js:492:13)\",\"_deep_error_code_\":400}"
}
```

**Comment by mgoria** [comment]
This issue is fixed in `deep-framework@1.9.11` version
