### ISSUE TITLE
[deep-core] Error on creating admin user

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#470]
```
b: Error on creating admin user: UserLambdaValidationException: PreSignUp failed with error {"errorType":"TypeError","errorMessage":"Cannot read property 'user' of null","errorStack":"TypeError: Cannot read property 'user' of null\n    at _class._initDBPartitionKey (/var/task/deep_modules/deep-core@1.9.15/lib.compiled/AWS/Lambda/Runtime.js:263:44)\n    at /var/task/deep_modules/deep-core@1.9.15/lib.compiled/AWS/Lambda/Runtime.js:133:16\n    at process._tickDomainCallback (node.js:407:9)","_deep_error_code_":400}. 
 b: Error on creating admin user: UserLambdaValidationException: PreSignUp failed with error {"errorType":"TypeError","errorMessage":"Cannot read property 'user' of null","errorStack":"TypeError: Cannot read property 'user' of null\n    at _class._initDBPartitionKey (/var/task/deep_modules/deep-core@1.9.15/lib.compiled/AWS/Lambda/Runtime.js:263:44)\n    at /var/task/deep_modules/deep-core@1.9.15/lib.compiled/AWS/Lambda/Runtime.js:133:16\n    at process._tickDomainCallback (node.js:407:9)","_deep_error_code_":400}.
    at Immediate._onImmediate (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Provisioning/Service/CognitoIdentityProviderService.js:1:3767)
    at processImmediate [as _immediateCallback] (timers.js:383:17) 
```

**Comment by ivignan** [comment]
@CCristi Is this still relevant?

**Comment by CCristi** [comment]
@ivignan yes

**Comment by ivignan** [comment]
@dsasov Why this issue was not tested within 48 hours?
