### ISSUE TITLE
Lambda fails with memory leak

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-framework#481]
Lambda fails with error:
```
(node) warning: possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit.
```
```
Trace
at process.addListener (events.js:239:17)
at Sandbox.run (/var/task/deep_modules/deep-core@1.9.20/lib.compiled/Runtime/Sandbox.js:64:25)
at Handler.run (/var/task/deep_modules/deep-core@1.9.20/lib.compiled/AWS/Lambda/Runtime.js:151:10)
at /var/task/deep_modules/deep-framework@1.10.22/lib.compiled/Framework.js:59:37
at Kernel.bootstrap (/var/task/deep_modules/deep-kernel@1.9.5/lib.compiled/Kernel.js:230:9)
at LambdaHandler.handler.KernelFromLambdaContext.bootstrap (/var/task/deep_modules/deep-framework@1.10.22/lib.compiled/Framework.js:58:56)
```

**Comment by AScripnic** [comment]
still fails:
```
2016-11-17T14:34:07.830Z	bf16c99b-acd2-11e6-96c7-1bcfa1a43a58	Trace
at process.addListener (events.js:239:17)
at Sandbox.run (/var/task/deep_modules/deep-core@1.9.21/lib.compiled/Runtime/Sandbox.js:65:25)
at _class.run (/var/task/deep_modules/deep-core@1.9.21/lib.compiled/AWS/Lambda/Runtime.js:151:10)
at /var/task/deep_modules/deep-framework@1.10.24/lib.compiled/Framework.js:59:37
at Kernel.bootstrap (/var/task/deep_modules/deep-kernel@1.9.5/lib.compiled/Kernel.js:230:9)
at LambdaHandler.handler.KernelFromLambdaContext.bootstrap (/var/task/deep_modules/deep-framework@1.10.24/lib.compiled/Framework.js:58:56)
```

**Comment by eistrati** [comment]
Apparently fixed.
