### ISSUE TITLE
[deep-db] TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-framework#558]
Please refer to this link for more details: https://travis-ci.org/MitocGroup/deep-framework/jobs/215345542#L2414

```shell
  70 passing (165ms)
  3 failing

  1) Vogels/ExtendModel Check method._findUntilLimit[Cb]() passes findOne* call:
     TypeError: Cannot read property 'apply' of undefined
      at Object._findUntilLimitCb (lib/Vogels/ExtendModel.js:18:5)
      at Context.<anonymous> (test/Vogels/ExtendModel.spec.js:106:31)
  2) Vogels/ExtendModel Check method._findUntilLimit[Cb]() passes findBy* call:
     TypeError: Cannot read property 'apply' of undefined
      at Object._findUntilLimitCb (lib/Vogels/ExtendModel.js:18:5)
      at Context.<anonymous> (test/Vogels/ExtendModel.spec.js:119:31)
  3) Vogels/ExtendModel Check method._findUntilLimit[Cb]() passes findBy*Paginated call:
     TypeError: Cannot read property 'apply' of undefined
      at Object._findUntilLimitCb (lib/Vogels/ExtendModel.js:18:5)
      at Context.<anonymous> (test/Vogels/ExtendModel.spec.js:135:31)
```

**Comment by avozicov** [comment]
Acceptance Criteria for the following issue is "Passed status for latest travis build run".
**Test Passed**
Please refer to the log file
https://travis-ci.org/MitocGroup/deep-framework/jobs/233855433
