### ISSUE TITLE
[deep-resource] Unable to parse data:  SyntaxError: Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-framework#560]
Please refer to this link for more details: https://travis-ci.org/MitocGroup/deep-framework/jobs/215345542#L3060

```shell
Unable to parse data:  SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at SuperagentResponse._parseLambda (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:11:126)
    at new SuperagentResponse (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:5:1)
    at Context.<anonymous> (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/test/Resource/SuperagentResponse.spec.js:68:26)
    at callFn (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:326:21)
    at Test.Runnable.run (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:319:7)
    at Runner.runTest (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:422:10)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:528:12
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:342:14)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:352:7
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

```shell
Unable to parse data:  SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at SuperagentResponse._parseLambda (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:11:126)
    at new SuperagentResponse (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:5:1)
    at Context.<anonymous> (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/test/Resource/SuperagentResponse.spec.js:99:26)
    at callFn (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:326:21)
    at Test.Runnable.run (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:319:7)
    at Runner.runTest (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:422:10)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:528:12
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:342:14)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:352:7
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

```shell
Unable to parse data:  SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at SuperagentResponse._parseLambda (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:11:126)
    at new SuperagentResponse (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:5:1)
    at Context.<anonymous> (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/test/Resource/SuperagentResponse.spec.js:110:26)
    at callFn (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:326:21)
    at Test.Runnable.run (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:319:7)
    at Runner.runTest (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:422:10)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:528:12
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:342:14)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:352:7
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

```shell
Unable to parse data:  SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at SuperagentResponse._parseLambda (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:11:126)
    at new SuperagentResponse (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/lib/Resource/SuperagentResponse.js:5:1)
    at Context.<anonymous> (/home/travis/build/MitocGroup/deep-framework/src/deep-resource/test/Resource/SuperagentResponse.spec.js:121:26)
    at callFn (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:326:21)
    at Test.Runnable.run (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:319:7)
    at Runner.runTest (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:422:10)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:528:12
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:342:14)
    at /home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:352:7
    at next (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by avozicov** [comment]
Acceptance Criteria for the following issue is "Passed status for latest travis build run".
**Test Passed**
Please refer to the log file
https://travis-ci.org/MitocGroup/deep-framework/jobs/233855433
