### ISSUE TITLE
[deep-framework] S3CoverageSynchronizer.es6: Access Denied

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-framework#561]
Please refer to this link for more details: https://travis-ci.org/MitocGroup/deep-framework/jobs/215345542#L3313

```shell
node-scripts/S3CoverageSynchronizer.es6 -> node-scripts/S3CoverageSynchronizer.js
unable to download: { AccessDenied: Access Denied
    at Request.extractError (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/home/travis/build/MitocGroup/deep-framework/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: 'us-west-2',
  time: 2017-03-27T01:03:14.017Z,
  requestId: '2EFA7409BCD822B8',
  extendedRequestId: '8xHVi6TjB8HfbH3yMSZoeack0s/k6g8kdbI5Aym3flnyb5GE0EpIkM+YuCGSapDgFlF8d3V+u3s=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 57.062415906818956 }
```

**Comment by avozicov** [comment]
Acceptance Criteria for the following issue is "Passed status for latest travis build run".
**Test Passed**
Please refer to the log file
https://travis-ci.org/MitocGroup/deep-framework/jobs/233855433
