### ISSUE TITLE
Lambda failing randomly after deep-account integration

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/deep-framework#567]
```
{
    "errorMessage": "{\"errorType\":\"Error\",\"errorMessage\":\"`value` required in setHeader(\\\"X-Amz-Security-Token\\\", value).\",\"errorStack\":\"Error: `value` required in setHeader(\\\"X-Amz-Security-Token\\\", value).\\n    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:342:11)\\n    at Request.request (/var/task/deep_modules/superagent@3.5.2/lib/node/index.js:1:6808)\\n    at Request.end (/var/task/deep_modules/superagent@3.5.2/lib/node/index.js:1:8434)\\n    at request.end (/var/task/deep_modules/deep-resource@1.12.5/lib.compiled/Resource/Request.js:751:17)\\n    at /var/task/deep_modules/deep-resource@1.12.5/lib.compiled/Resource/Request.js:774:11\\n    at /var/task/deep_modules/deep-resource@1.12.5/lib.compiled/Resource/Request.js:978:9\\n    at /var/task/deep_modules/deep-resource@1.12.5/lib.compiled/Resource/Request.js:1016:9\\n    at null._onTimeout (/var/task/deep_modules/deep-security@1.12.1/lib.compiled/Token.js:294:11)\\n    at Timer.listOnTimeout (timers.js:92:15)\",\"_deep_error_code_\":400}"
}
```

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- There should not be errors when calling a lambda from "Account"
component
- "Roles" related lambdas were used to validate the issue
<img width="1280" alt="screen shot 2017-06-20 at 13 20 18" src="https://user-images.githubusercontent.com/12330493/27330158-eb53b7fa-55c0-11e7-9009-5404a58c71fa.png">
