### ISSUE TITLE
Unable to write to dynamodb with integrated deep-account

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/deep-framework#591]
Calling a lambda with admin user authenticated results in a "Database operation failed" error (see the trace bellow)

```
{ "errorMessage": "{\"errorType\":\"DatabaseOperationException\",\"errorMessage\":\"Database operation failed. AccessDeniedException: User: arn:aws:sts::722084099005:assumed-role/DeepDevBackendRoleb9e14b705347f79a/backend-role-DeepDevBackendRoleb9e14b705347f79a is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:722084099005:table/DeepDevContent5347f79a\",\"errorStack\":\"DatabaseOperationException: Database operation failed. AccessDeniedException: User: arn:aws:sts::722084099005:assumed-role/DeepDevBackendRoleb9e14b705347f79a/backend-role-DeepDevBackendRoleb9e14b705347f79a is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:722084099005:table/DeepDevContent5347f79a\\n    at model.createItem (/var/task/bootstrap.js:7:898892)\\n    at /var/task/bootstrap.js:7:2386449\\n    at /var/task/bootstrap.js:7:2383954\\n    at /var/task/bootstrap.js:7:1197378\\n    at Response._dynamoDbDocumentClient.(anonymous function) (/var/task/bootstrap.js:7:1202388)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:358:18)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at Request.RESET_RETRY_STATE (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:398:9)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:101:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:230:11)\\n    at emitNone (events.js:91:20)\\n    at IncomingMessage.emit (events.js:185:7)\\n    at endReadableNT (_stream_readable.js:974:12)\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\",\"_deep_error_code_\":500}" }
```

**Comment by AlexanderC** [comment]
Fixed in https://github.com/MitocGroup/deep-microservices-account/pull/318

**Comment by avozicov** [comment]
_Test Passed_
Acceptance Criteria:
- There should not be errors when calling a lambda from "Account" 
component 
- "Roles" related lambdas were used to validate the issue 
<img width="1280" alt="screen shot 2017-06-20 at 13 20 18" src="https://user-images.githubusercontent.com/12330493/27328577-42c1d040-55bb-11e7-9eee-e8a18bc0aaf5.png">
