### ISSUE TITLE
[deep-security] The security token included in the request is expired

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/deep-framework#592]
Trying to do `https://api-dev.adtechmedia.io/v1/atm-admin/property/update-config` from WP Plugin with Api Key `249oc01e6ea9b46c0343d3bc6922bb0e55c288` getting:

```
{ "errorMessage": "{\"errorType\":\"ExpiredTokenException\",\"errorMessage\":\"The security token included in the request is expired\",\"errorStack\":\"ExpiredTokenException: The security token included in the request is expired\\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:230:11)\\n    at emitNone (events.js:91:20)\\n    at IncomingMessage.emit (events.js:185:7)\\n    at endReadableNT (_stream_readable.js:974:12)\\n    at /var/task/bootstrap.js:7:895261\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)\",\"_deep_error_code_\":500}" }
```

> I'm using `deepify v3.0.31 (built: Wed Apr 26 17:28:33 EEST 2017)` and deployed today with latest changes

**Comment by mgoria** [comment]
Cannot reproduce.

**Comment by mgoria** [comment]
Steps to test:

1. Register a new client via API to receive an api key
2. Create a new property using this api key
3. Wait 1 hour and try invoking `/atm-admin/property/update-config` with the same api key

Expected result: delayed request should succeed without throwing with `The security token included in the request is expired`

**Comment by avozicov** [comment]
Test execution is blocked by the following issue
https://github.com/MitocGroup/deep-framework/issues/529

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- "property/update-config" endpoint should not fail on calling it again
<img width="1280" alt="screen shot 2017-06-23 at 11 18 32" src="https://user-images.githubusercontent.com/12330493/27472871-c0db0c84-5805-11e7-845c-b28d63230480.png">
