### ISSUE TITLE
500 error on calling `property/retrieve`

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/deep-framework#609]
Error on calling `https://api-dev.adtechmedia.io/v1/atm-admin/property/retrieve?Id=4ba6f120-446f-11e7-9968-696ca9f5ff87` with `X-Api-Key`

```
{
    "errorMessage": "{\"errorType\":\"ExpiredTokenException\",\"errorMessage\":\"The security token included in the request is expired\",\"errorStack\":\"ExpiredTokenException: The security token included in the request is expired\\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:256:13)\\n    at emitNone (events.js:91:20)\\n    at IncomingMessage.emit (events.js:185:7)\\n    at endReadableNT (_stream_readable.js:974:12)\\n    at /var/task/bootstrap.js:143852:31\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)\",\"_deep_error_code_\":500}"
}
```

Steps to reproduce:
1. Call this endpoint with a token
2. Wait 1 hours or so
3. Call the same endpoint

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- property-retrieve endpoint should not fail when calling it with two times (after 1 hour after first call)
<img width="1280" alt="screen shot 2017-06-22 at 19 39 44" src="https://user-images.githubusercontent.com/12330493/27445550-d6b1d520-5782-11e7-9334-353e586e5cbe.png">
<img width="1280" alt="screen shot 2017-06-22 at 19 39 49" src="https://user-images.githubusercontent.com/12330493/27445549-d6b1a4d8-5782-11e7-992b-4e88a630cfb1.png">
